### ISSUE TITLE
How to use this.$axios with existing credentials

### ISSUE THREAD

**Issue by sotnaspina** [blogui91/quasar-oauth-laravel#1]
Hello!
Great material, it helped a lot.
But, I need a help, how do I make other api requests using the existing self-build settings?

Example: this.$axios.get('sectors').then()

Thank you, hug.

**Comment by neomobil** [comment]
This is my method to use existing credentials.
submit () {
      this.$q.loading.show({
        delay: 400
      })
      const form = new FormData()
      form.append('username', this.email)
      form.append('password', this.password)
      form.append('grant_type', 'password')
      form.append('client_id', 'use_your_id')
      form.append('client_secret', 'use_your_secret')
      const options = {
        method: 'POST',
        headers: {
          'Content-Type': 'text/plain'
        },
        data: form,
        url: '/oauth/token'
      }
      this.$axios(options)
        .then(response => {
          this.$store.commit('base/setToken', response.data.access_token)
        })
        .then(() => {
          this.$axios({
            method: 'GET',
            url: 'api/user',
            headers: {
              'Accept': 'application/json',
              'Authorization': `Bearer ${this.$store.state.base.token}`
            }
          }).then(response => {
            this.$store.commit('base/setUser', response.data.data)
            this.$router.push('/home')
          })
        })
        .catch(error => {
          this.catch(error)
          this.$q.loading.hide()
        })
    }

**Comment by blogui91** [comment]
Hello @sotnaspina are you asking for use something like ```Sector.get().then()``` instead of ```this.$axios.get('sectors').then() ``` ?
If so you just to need to create a new file in services folder
```
import Service from 'easy-requests'
import Config from 'src/config'

class Sector extends Service {
  constructor () {
    super()
    this.config.origin = Config('api.api_url')
    this.config.endpoint = '/sectors/'
  }
}
export default Sector
```
In that way you can make ajax calls in any component just by importing this file.

```
import Sector from 'services/sector.service'
Sector.get()  // returns the list of sectors
Sector.find(id) // Return only one sector
Sector.update(id, data) // Updates an existent sector
Sector.delete (id) // Deletes a sector
```

all these methods returns a promise, you can use then or async/await

For more information you can check this link https://github.com/blogui91/easy-requests#readme

**Comment by sotnaspina** [comment]
Master @blogui91, thank you very much!!
It worked perfectly, that's right.
